name: Database Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          sudo apt-get -yqq install postgresql-client
          export PGPASSWORD=$DATABASE_PASSWORD

      - name: Run SQL Script
        run: |
          psql -h $DATABASE_HOST -u $DATABASE_USERNAME -d $DATABASE_NAME -a -f sample_table.sql

env:
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
